[1주차] 정렬 알고리즘 정리
KB-IT-s-Your-Life-Study/KB_algorithm_study pull request #2
Opened 2024-06-08 04:15 UTC by cheongwonyoung

2024-06-08 04:20 UTC, cheongwonyoung commented
기수 정렬에 대한 정리가 부족하여 따로 추가하도록 하겠습니다 !

2024-06-09 08:19 UTC, SangminHann requested changes
안정정렬인지와 제자리 정렬인지의 여부도 있으면 좋겠습니다. 
또한 쉘정렬에 대한 설명도 해주세요!

2024-06-09 08:19 UTC, SangminHann commented on 정렬알고리즘_정원영/정렬알고리즘 정리_정원영.md
> +실제로 측정해보면 버블정렬에 비해서는 조금 더 빠르다.
버블정렬보다 왜 빠른지 궁금합니다

2024-06-09 08:19 UTC, SangminHann commented on 정렬알고리즘_정원영/정렬알고리즘 정리_정원영.md
> +- 단점 : 퀴정렬과 같은 다른 O(NlogN)에 비해 실제 측정에서 느리다.
퀴 오타났어요 ㅋㅋㅋ 퀵정렬 보다 느린이유도 궁금합니다.

2024-06-09 08:19 UTC, SangminHann commented on 정렬알고리즘_정원영/정렬알고리즘 정리_정원영.md
> +
힙정렬이 어떻게 구현되어 있는지 궁금합니다.

2024-06-09 08:19 UTC, SangminHann commented on 정렬알고리즘_정원영/정렬알고리즘 정리_정원영.md
> +
보통 퀵정렬이 병합정렬보다 빠르다고 합니다. 그이유도 적어주세요

2024-06-09 08:19 UTC, SangminHann commented on 정렬알고리즘_정원영/정렬알고리즘 정리_정원영.md
> +```java
버블정렬 개선 코드입니다.
```
boolean swapped;

for (int i = 0; i < arr.length - 1; i++) {
    swapped = false;

	for (int j = 0; j < arr.length - 1 - i; j++) {

	    if (arr[j] > arr[j + 1]) {
	        int tmp = arr[j];
	        arr[j] = arr[j + 1];
	        arr[j + 1] = tmp;
	        swapped = true;
	    }
	}

    if (!swapped) {
        break;
    }
}
```

2024-06-09 10:49 UTC, sooojChoi reviewed
시간이 된다면 계수 정렬에 대해 같이 살펴보는 것도 좋을 것 같아요!

[https://gyoogle.dev/blog/algorithm/Counting%20Sort.html](url)

2024-06-09 23:52 UTC, seowonn commented on 정렬알고리즘_정원영/정렬알고리즘 정리_정원영.md
> +    int pivot = start;
pivot은 아무 위치나 잡아서 시작해도 되는건가요?

2024-06-09 23:52 UTC, seowonn commented on 정렬알고리즘_정원영/정렬알고리즘 정리_정원영.md
> +### 병합정렬
앞쪽 3개 정렬 중에는 삽입 정렬이 시간복잡도면에서 제일 효율적인 것 같아 보이는데 퀵하고 병합정렬 간에는 둘 다 비슷하게 자주 쓰이나요?

2024-06-10 03:11 UTC, gogoyubae commented
병합정렬이나 힙이 가장 효율적으로 보이는데, 다른 정렬을 사용해야만 하는 사례가 있는지 궁금합니다.

2024-06-18 00:17 UTC, merged